### ISSUE TITLE
Viewing a post turns the screen black

### ISSUE THREAD

**Issue by danielwis** [Memmy-App/memmy#1017]
### Check for open issues

- [X] I have verified that another issue for this is not open, or it has been closed and has not been fixed.

### Minimal reproducible example

I just logged in, clicked on a post, and after a ~1s delay the screen turns black. I can’t seem to fix it by swiping or anything either.

### Expected Behavior

The screen should not turn black.

### Version

1.0 (20)

### App Store or TestFlight?

TestFlight

### iOS Version

16.x

### Device

iPhone X

**Comment by danielwis** [comment]
Video of it happening, as I couldn’t find the button to add media while opening the issue:
https://github.com/Memmy-App/memmy/assets/46249158/b3df55d2-7613-4be3-817c-dc909305f677

**Comment by gkasdorf** [comment]
Was just about to post as "fixed now" thinking this was an old one, looks new. I'll see if I can figure anything out to fix that. Cheers.

**Comment by gkasdorf** [comment]
@danielwis Did this resolve itself or were you *never* able to use the app?

**Comment by danielwis** [comment]
Nope, still happening on 1.0 (35) and I'm able to use the app for everything else.

Did some basic troubleshooting just now and it seems to only happen for posts with comments. Not knowledgeable enough in React to contribute anything substantial, I'm afraid, but here are a few scenarios and their outcomes in case they help with debugging ("viewing" meaning "tapping on the post as shown in the video to see comments etc."):

- Viewing any post with comments: crash
- Viewing a few different posts without comments: seems to work fine
- Viewing an image post by clicking on the image itself (regardless of comments): seems to work fine
- Viewing the comments of the same image post as directly above: crash

**Comment by gkasdorf** [comment]
Huh...definitely cannnot reproduce that myself, so that's weird. Give me like...10 minutes here to setup that log file sending and let's see if there is something in there that can point us in the right direction.

**Comment by danielwis** [comment]
Sure, let me know if you need me to do anything.

**Comment by gkasdorf** [comment]
@danielwis Alright, I'm building and submitting now. Should be ~10 minutes. Once you see the build, can you please do the following:

1. Go to the settings tab and press "Clear Debug Log" at the bottom of the main settings screen
2. Restart the app
3. Do whatever it is that's causing issues
4. You may or may not see a sad face screen now (I think you were being shown just the blank error screen I had there before). If you do, simply press "Email Debug Log" and I will receive it. If you don't see that screen, restart the app again and head to the main settings screen and press "Email Debug Log".

Also:
1. What instance are you on?
2. What version of Lemmy is that instance running (backend)?

Thanks!

**Comment by danielwis** [comment]
> Also:
> 
> 1. What instance are you on?
> 2. What version of Lemmy is that instance running (backend)?

I'm on lemmy.world, BE seems to be 0.18.5. 

> Thanks!

Right back at ya!

**Comment by gkasdorf** [comment]
@danielwis Ok, should be available now. Let me know once you've sent that debug log over and I'll take a peek.

**Comment by danielwis** [comment]
Yup, just came in! I've sent the log, hopefully you can figure it out from there.

**Comment by gkasdorf** [comment]
What are your swipe options, particularly for the right options?

**Comment by gkasdorf** [comment]
Ah, just repro'd it. Give me a moment!

**Comment by gkasdorf** [comment]
@danielwis Fixed now and building. Thanks! https://github.com/Memmy-App/memmy/commit/76c301527303eaaf02c357d3797b30dced70d240

**Comment by danielwis** [comment]
Fantastic, I just updated + tested it and everything works perfectly. Huge thanks for your quick response times and dedication!
