### ISSUE TITLE
Status bar text and icons in System theme mismatch

### ISSUE THREAD

**Issue by qauff** [Memmy-App/memmy#395]
**Description**
Since the System Theme has been introduced, it seems that the status bar text and icons are the same colour scheme as the theme selected before the System theme is enabled.

When system theme is disabled, if you select Light theme, then enable system theme: in dark mode, the status bar icons and text are light theme (dark, blends into the Dark theme).

Vice versa too, when system theme is disabled if you select a Dark theme, then enable system theme: in light mode, the status bar icons and text are dark theme (light, blends with Light theme).

**To Reproduce**
1. Make sure your iOS is on Light theme
2. In Memmy, while `Match System Light/Dark Theme` is disabled, select the Light theme. 
3. Enable `Match System Light/Dark Theme`. 
4. Make sure Light theme is selected for Light, and a Dark theme is selected for Dark. 
5. Toggle your iOS theme to Dark, and look at the status bar.

**Expected behavior**
Status bar icons and text to match the desired selected theme.

**Screenshots**
***Light base***
![image](https://github.com/Memmy-App/memmy/assets/15840269/09a2d4f2-11ec-4b21-a130-b453f39a2562)
![image](https://github.com/Memmy-App/memmy/assets/15840269/0e540cd5-9e3f-4980-9dcc-a4661e309aee)
![image](https://github.com/Memmy-App/memmy/assets/15840269/3c345d3e-ec79-4682-8b39-329a22881bb1)

***Dark base***
![image](https://github.com/Memmy-App/memmy/assets/15840269/126a11a8-9661-4466-9937-78a8b659964c)
![image](https://github.com/Memmy-App/memmy/assets/15840269/bf8f7a13-e79c-4eba-88b1-7ac41c3dd05d)
![image](https://github.com/Memmy-App/memmy/assets/15840269/a100364a-8b9a-439b-8eff-b4c0d1c4522a)

**Smartphone**
 - Device: iPhone 12 Pro
 - OS: iOS 16.5.1

**Comment by gkasdorf** [comment]
Fixed in next build.

**Comment by qauff** [comment]
> Fixed in next build.

I just updated to the latest build in TestFlight, still seeing the issue unfortunately.

**Comment by qauff** [comment]
Just updated to version 0.1.0 (2) in TestFlight. The issue is still persistent. @gkasdorf was the fix meant to be in this latest build?
