### ISSUE TITLE
After returning to the app, the app briefly swiches to light theme

### ISSUE THREAD

**Issue by pitrisss** [Memmy-App/memmy#754]
**Describe the bug**
After returning to the app, the app briefly swiches to light theme. Seems to me like it happens everytime, after waking it from sleep. Doesn't happend if the app starts again.

**To Reproduce**
1. Open app
2. Go to desktop
3. Reopen the app
4. Wait few seconds

**Expected behavior**
I would expect, that it does not switch theme.

**Screenshots**
https://github.com/Memmy-App/memmy/assets/19386789/db8b8fe7-52f5-4023-a8c9-5e6710b4a59e

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Mini
 - OS: iOS
 - Version 16.5.1(c)

**Comment by eoddc5** [comment]
I have never seen this nor can I get this to reproduce

@gkasdorf or @sgriff96 either of you have any ideas?

**Comment by Taxxor90** [comment]
Here too
iPhone 12 Pro
iOS 16.5.1(c)
App version 0.4(2)

It only happens when you set it to use light/dark according to your system setting.
Played around with it a bit and for me, it's switching to whatever you've set as the light theme for a second before going back to the set dark theme.

**Comment by ecabr** [comment]
This also happens to me, dark theme to light theme and then back to dark theme, or light theme to dark theme and then back to light theme.

iPhone 13
iOS 16.5.1 (c)
App version 0.4 (2)

**Comment by theycallmebeez** [comment]
Cannot reproduce. Using iOS 17 on iPhone 13. Latest app update 0.4 (2)

**Comment by jderose9** [comment]
Seems to be a regression in .4. Only happens when the app restarts after iOS has unloaded it from ram, not just put briefly in background.

**Comment by sgriff96** [comment]
I assume it's some logic with the match system theme that's causing issues with this

**Comment by jderose9** [comment]
I’m guessing it’s related to the react native update. There’s a couple similar issues open on their repo, though they pre-date the current release. Still, maybe one of the workarounds described there could take care of it.

https://github.com/facebook/react-native/issues/35972

https://github.com/facebook/react-native/issues/36713

**Comment by qauff** [comment]
Getting same issue with latest 0.5 (3). Glitches to dark theme and back for me.

**Comment by gkasdorf** [comment]
Let's see if I can fix this.

**Comment by gkasdorf** [comment]
Fixed! Not sure how this *ever* worked correctly but anyway 🤷

**Comment by gkasdorf** [comment]
Ah, ok. There is an open issue with React Native about this like @jderose9 mentioned. https://github.com/facebook/react-native/issues/35972

For now I've implemented a hack mentioned in that issue for this. Will re-vist at a later time.

**Comment by TheFunkyMonk** [comment]
This is still happening to me. Usually when I open the app, and it does seem to only be tied to the “match system theme” option. 

iPhone 14 Pro
iOS 16.15.1(c)
Memmy 0.4 (2)

**Comment by gkasdorf** [comment]
It's fixed now, but Apple has not approved the updated build yet for the App Store. @TheFunkyMonk
